repos:

  # - repo: ...

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: <git sha or tag>
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--types, feat, fix, docs, style, refactor, test, chore] # optional: list of Conventional Commits types to allow